routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use Illuminate\Support\Facades\Route;

Route::get('/',  'App\Http\Controllers\User\HomeController@index')->name('home');
Route::get('product/{product}', 'App\Http\Controllers\User\ProductController@product')->name('product');
Route::get('post/category/{category}', [\App\Http\Controllers\User\HomeController::class, 'category'])->name('category');


Route::get('admin/home', [HomeController::class, 'index'])->name('admin.home');

Route::resource('admin/products', App\Http\Controllers\Admin\ProductController::class);
Route::resource('admin/category', App\Http\Controllers\Admin\CategoryController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductRequest $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(ProductRequest $request)
    {
        if($request->hasFile('image1')){
            $imageName = $request->image1->store('public/images');
        }
        $request['image'] = $imageName;

        Product::create($request->input());
        return redirect(route('products.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $product = Product::where('id', $id)->first();
        $categories = Category::all();
        return view('admin.product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductRequest $request
     * @param int $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(ProductRequest $request, $id)
    {

        if($request->hasFile('image1')){
            $imageName = $request->image1->store('public/images');
            $request['image'] = $imageName;
        }
        Product::where('id', $id)->update($request->except('_token', '_method', 'image1'));
        return redirect(route('products.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Product::where('id', $id)->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/User/ProductController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\User\Post;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('user.index');
    }

    /**
     * @param Product $product
     * @return Application|Factory|View
     */
    public function product(Product $product)
    {
        $categories = Category::all();
        return view('user.product', compact('product', 'categories'));
    }


}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5//bootstrap-wysihtml5.min.css') }}">
    <link rel="stylesheet" href="{{ asset('user/css/prism.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/css/select2.min.css') }}">
@endsection

@section('admin-main-content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Create New Product</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item active">Create New Product</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- inserted from general form elements file -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Titles</h3>
                        </div>
                        <!-- /.card-header -->
                        @include('includes.messages')
                        <!-- form start -->
                        <form role="form" action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-5 mr-4">
                                        <div class="form-group">
                                            <label for="title">Product Title</label>
                                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
                                        </div>
                                        <div class="form-group">
                                            <label for="price">Product Price</label>
                                            <input type="text" class="form-control" id="price" name="price" placeholder="Enter price">
                                        </div>

                                        <div class="form-group">
                                            <label for="subtitle">Subtitle</label>
                                            <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Enter subtitle">
                                        </div>
                                    </div>
                                    <div class="col-lg-5 ml-3">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select class="form-control" name="category_id">
                                                @foreach($categories as $category)--}}
                                                    <option value="{{ $category->id }}">{{ $category->categoryTitle }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="stock">Availability</label>
                                            <select class="form-control" name="stock">
                                                <option selected="selected" value="1">Available</option>
                                                <option value="0">Not Available</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="image1">File input</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" id="image" name="image1" style="cursor: pointer">
                                                    <label class="custom-file-label" for="image">Choose file</label>
                                                    <input type="hidden" name="image">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card card-outline card-info">

                                <div class="card-body pad">
                                    <div class="mb-3">
                                        <textarea class="textarea" placeholder="Place some text here" name="description" style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                    </div>
{{--                                    <p class="text-sm mb-0">--}}
{{--                                        Editor <a href="https://github.com/summernote/summernote">Documentation and license--}}
{{--                                            information.</a>--}}
{{--                                    </p>--}}
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="{{ route('products.index') }}" class="btn btn-warning">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('admin-footer')
    <!-- Summernote -->
{{--    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>--}}
    <script src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('user/js/prism.js') }}"></script>
    <script src="{{ asset('admin/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.select2').select2();
            bsCustomFileInput.init();
        });
        // $(function () {
        //     // Summernote
        //     $('.textarea').summernote()
        // })
        $(function () {
            CKEDITOR.replace('description');
            $('.textarea').wysihtml5();
        });
    </script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/css/select2.min.css') }}">
@endsection

@section('admin-main-content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Post Editor</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item active">Post Editor</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- inserted from general form elements file -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Titles</h3>
                        </div>
                        <!-- /.card-header -->
                    @include('includes.messages')
                    <!-- form start -->
                        <form role="form" action="{{ route('products.update', $product->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-5 mr-4">
                                        <div class="form-group">
                                            <label for="title">Product Title</label>
                                            <input type="text" class="form-control" id="title" name="title" value="{{ $product->title }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="subtitle">Product Price</label>
                                            <input type="text" class="form-control" id="price" name="price" value="{{ $product->price }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="slug">Subtitle</label>
                                            <input type="text" class="form-control" id="subtitle" name="subtitle" value="{{ $product->subtitle }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-5 ml-3">
                                        <div class="form-group" data-select2-id="37">
                                            <label>Select Categories</label>
                                            <select class="form-control" name="category_id">
                                                @foreach($categories as $category)
                                                    <option value="{{ $category->id }}"
                                                            @if($product->category->id == $category->id)
                                                                selected
                                                            @endif
                                                    >{{ $category->categoryTitle }}</option>
                                                @endforeach
                                            </select>
                                            {{--                                                <span class="select2 select2-container select2-container--default select2-container--below" dir="ltr" data-select2-id="8" style="width: 100%;"><span class="selection"><span class="select2-selection select2-selection--multiple" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-disabled="false"><ul class="select2-selection__rendered"><li class="select2-selection__choice" title="Alabama" data-select2-id="49"><span class="select2-selection__choice__remove" role="presentation">×</span>Alabama</li><li class="select2-selection__choice" title="Delaware" data-select2-id="50"><span class="select2-selection__choice__remove" role="presentation">×</span>Delaware</li><li class="select2-search select2-search--inline"><input class="select2-search__field" type="search" tabindex="0" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" role="searchbox" aria-autocomplete="list" placeholder="" style="width: 0.75em;"></li></ul></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>--}}
                                        </div>
                                        <div class="form-group">
                                            <label for="slug">Availability</label>
                                            <select class="form-control" style="width: 100%;" name="stock">
                                                <option value="1" @if($product->stock == 1) selected @endif>Available</option>
                                                <option value="0" @if($product->stock == 0) selected @endif>Not Available</option>
                                            </select>
                                        </div>
                                        <div class="row justify-content-between">
                                            <div class="form-group col-lg-10">
                                                <label for="file">File input</label>
                                                <div class="input-group">
                                                    <div class="custom-file">
                                                        <input type="file" class="custom-file-input" id="image1" name="image1">
                                                        <label class="custom-file-label" for="image">Choose file</label>
                                                        <input type="hidden" name="image">
                                                    </div>
                                                    <div class="input-group-append">
                                                        <span class="input-group-text" id="imageUpload">Upload</span>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card card-outline card-info">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        Post body
                                        <small>Simple and fast</small>
                                    </h3>
                                    <!-- tools box -->
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                                                title="Collapse">
                                            <i class="fas fa-minus"></i></button>
                                    </div>
                                    <!-- /. tools -->
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body pad">
                                    <div class="mb-3">
                                        <textarea class="textarea" placeholder="Place some text here" name="description" style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $product->description }}</textarea>
                                    </div>
                                    <p class="text-sm mb-0">
                                        Editor <a href="https://github.com/summernote/summernote">Documentation and license
                                            information.</a>
                                    </p>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                                <a href="{{ route('products.index') }}" class="btn btn-warning">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('admin-footer')
    <!-- Summernote -->
    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.select2').select2();
            bsCustomFileInput.init();
        });
        $(function () {
            // Summernote
            $('.textarea').summernote()
        })
    </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('admin-main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Products list</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item active">Products list</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title font-weight-bold">Products</h1>
                    <a class="offset-lg-5 btn btn-success" href="{{ route('products.create') }}">Create New Product</a>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Product DataTable</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Product Title</th>
                                    <th>Subtitle</th>
                                    <th>Category</th>
                                    <th>Price</th>
                                    <th>Stock</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($products as $product)
                                    <tr>
                                        <td>{{ $loop->index +1 }}</td>
                                        <td>{{ $product->title }}</td>
                                        <td>{{ $product->subtitle }}</td>
                                        <td>{{ $product->category->categoryTitle }}</td>
                                        <td>{{ $product->price }}</td>
                                        <td>{{ $product->stock == 1 ? 'Available' : 'Not Available' }}</td>
                                        <td><a class="btn btn-success btn-sm" href="{{ route('products.edit', $product->id) }}"><i class="fas fa-pen-square"></i> Edit</a></td>
                                        <form action="{{ route('products.destroy', $product->id) }}" method="post" id="deleteForm-{{ $product->id }}" style="display: none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <td><a class="btn btn-danger btn-sm" href="" onclick="
                                            if(confirm('Are you sure, You want to delete this product?')){
                                                event.preventDefault();
                                                document.getElementById('deleteForm-{{ $product->id }}').submit();
                                           }else{
                                                event.preventDefault();
                                           }"><i class="fas fa-trash-alt"></i> Delete</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>S.No</th>
                                    <th>Product Title</th>
                                    <th>Subtitle</th>
                                    <th>Category</th>
                                    <th>Price</th>
                                    <th>Stock</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    Footer
                </div>
                <!-- /.card-footer-->
            </div>
            <!-- /.card -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('admin-footer')
    <!-- DataTables -->
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin./plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@endsection